Traceback (most recent call last):
  File "/Users/adriankriger/miniconda3/envs/geo3D_wrkshp/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/adriankriger/miniconda3/envs/geo3D_wrkshp/lib/python3.9/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/adriankriger/miniconda3/envs/geo3D_wrkshp/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Users/adriankriger/miniconda3/envs/geo3D_wrkshp/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/adriankriger/miniconda3/envs/geo3D_wrkshp/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/adriankriger/miniconda3/envs/geo3D_wrkshp/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/adriankriger/miniconda3/envs/geo3D_wrkshp/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
cm = cityjson.load(path=jparams['cjsn_solid']) #-- citjsnClean_uEstate10m.json in the result folder
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[4], line 1[0m
[0;32m----> 1[0m cm [38;5;241m=[39m [43mcityjson[49m[38;5;241;43m.[39;49m[43mload[49m[43m([49m[43mpath[49m[38;5;241;43m=[39;49m[43mjparams[49m[43m[[49m[38;5;124;43m'[39;49m[38;5;124;43mcjsn_solid[39;49m[38;5;124;43m'[39;49m[43m][49m[43m)[49m [38;5;66;03m#-- citjsnClean_uEstate10m.json in the result folder[39;00m

File [0;32m~/miniconda3/envs/geo3D_wrkshp/lib/python3.9/site-packages/cjio/cityjson.py:65[0m, in [0;36mload[0;34m(path, transform)[0m
[1;32m     58[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mload[39m(path, transform: [38;5;28mbool[39m [38;5;241m=[39m [38;5;28;01mTrue[39;00m):
[1;32m     59[0m [38;5;250m    [39m[38;5;124;03m"""Load a CityJSON file for working with it though the API[39;00m
[1;32m     60[0m 
[1;32m     61[0m [38;5;124;03m    :param path: Absolute path to a CityJSON file[39;00m
[1;32m     62[0m [38;5;124;03m    :param transform: Apply the coordinate transformation to the vertices (if applicable)[39;00m
[1;32m     63[0m [38;5;124;03m    :return: A CityJSON object[39;00m
[1;32m     64[0m [38;5;124;03m    """[39;00m
[0;32m---> 65[0m     [38;5;28;01mwith[39;00m [38;5;28;43mopen[39;49m[43m([49m[43mpath[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mr[39;49m[38;5;124;43m'[39;49m[43m)[49m [38;5;28;01mas[39;00m fin:
[1;32m     66[0m         [38;5;28;01mtry[39;00m:
[1;32m     67[0m             cm [38;5;241m=[39m CityJSON(file[38;5;241m=[39mfin)

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: './result/citjsnClean_wEstate5m3D.json'

